// Generated by CoffeeScript 1.9.1
var axis, cam_pos, camera, canvasFrame, cube, cubes, geometry, i, initCamera, initObject, initThree, loops, make_pos, make_rotate, material, renderer, requestAnimationFrame, rnd, scene, step, threeStart, y;

window.addEventListener("load", function() {
  return threeStart();
});

threeStart = function() {
  initThree();
  initCamera();
  initObject();
  loops();
};

canvasFrame = void 0;

renderer = void 0;

scene = void 0;

initThree = function() {
  canvasFrame = document.createElement('div');
  renderer = new THREE.WebGLRenderer();
  if (!renderer) {
    alert("initialize three.js");
  }
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(canvasFrame);
  canvasFrame.appendChild(renderer.domElement);
  renderer.setClearColor('black', 1.0);
  scene = new THREE.Scene();
};

camera = void 0;

initCamera = function() {
  camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 10000);
  camera.position.set(500, 500, 500);
  camera.up.x = 0;
  camera.up.y = 0;
  camera.up.z = 1;
  camera.lookAt({
    x: 0,
    y: 0,
    z: 0
  });
};


/*オブジェクト定義 */

axis = void 0;

geometry = void 0;

material = void 0;

cube = void 0;

cubes = (function() {
  var j, results;
  results = [];
  for (i = j = 0; j <= 100; i = ++j) {
    results.push(0);
  }
  return results;
})();

initObject = function() {
  var index, j, len;
  geometry = new THREE.BoxGeometry(10, 10, 10);
  material = new THREE.MeshNormalMaterial();
  for (index = j = 0, len = cubes.length; j < len; index = ++j) {
    i = cubes[index];
    cubes[index] = new THREE.Mesh(geometry, material);
    scene.add(cubes[index]);
  }
};

step = 0;

requestAnimationFrame = window.mozRequestAnimationFrame;

y = 2;

rnd = function(x) {
  return Math.floor(Math.random() * x);
};

make_pos = function(O, X, Y, Z) {
  O.position.set(rnd(X), rnd(Y), rnd(Z));
};

make_rotate = function(O, X, Y, Z) {
  O.rotation.set(rnd(X), rnd(Y), rnd(Z));
};

cam_pos = function(camera, X, Y, Z) {
  camera.position.x = X;
  camera.position.y = Y;
  camera.position.z = Z;
};

loops = function() {
  var index, j, len;
  for (index = j = 0, len = cubes.length; j < len; index = ++j) {
    i = cubes[index];
    if (index % 2 === 0) {
      make_pos(i, rnd(4), rnd(y++), rnd(y++));
      make_rotate(i, rnd(5), rnd(4), rnd(-10));
      camera.lookAt({
        x: rnd(50),
        y: rnd(50),
        z: rnd(50)
      });
    } else {
      make_pos(i, rnd(-10), rnd(-(y--) * 10), rnd(-(y--) * 10));
      make_rotate(i, rnd(-2 * 10), rnd(-40), rnd(-5));
      cam_pos(camera, 200, 200, 200);
    }
  }
  renderer.render(scene, camera);
  requestAnimationFrame(loops);
};

this.rnd = rnd;

//# sourceMappingURL=get_start3.js.map
