// Generated by CoffeeScript 1.9.1
var animate, camera, curve, geometry, initCamera, initObject, initThree, line, material, next, pos, pos1, renderer, scene, start, target, tween, tweens;

target = void 0;

renderer = void 0;

scene = void 0;

line = void 0;

tween = void 0;

pos1 = void 0;

initThree = function() {
  var canvasFrame;
  canvasFrame = document.createElement('div');
  renderer = new THREE.WebGLRenderer();
  if (!renderer) {
    alert("initialize three.js");
  }
  renderer.setSize(window.innerWidth, window.innerHeight);
  document.body.appendChild(canvasFrame);
  canvasFrame.appendChild(renderer.domElement);
  renderer.setClearColor('black', 1.0);
  scene = new THREE.Scene();
};

camera = void 0;

initCamera = function() {
  camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 1, 10000);
  camera.position.z = 500;
};


/*オブジェクト定義 */

geometry = void 0;

material = void 0;

curve = void 0;

pos = void 0;

next = void 0;

initObject = function() {
  var SUBDIVISIONS;
  SUBDIVISIONS = 20;
  geometry = new THREE.Geometry();
  pos = {
    x: 0,
    y: 0,
    z: 0
  };
  next = {
    x: pos.x + 1,
    y: pos.y,
    z: pos.z
  };

  /*
  curve = new THREE.QuadraticBezierCurve3()
  curve.v0 = new THREE.Vector3(0, 0, 0)
  curve.v1 = new THREE.Vector3(0, 100, 0)
  curve.v2 = new THREE.Vector3(0, 200, 0)
  
  for j in [0..20]
    geometry.vertices.push( curve.getPoint(j / SUBDIVISIONS) )
   */
  geometry.vertices.push(pos);
  geometry.vertices.push(next);
  material = new THREE.LineBasicMaterial({
    color: 0xffffff,
    linewidth: 50
  });
  line = new THREE.Line(geometry, material);
  scene.add(line);
};

tweens = function() {
  target = {
    x: 400,
    y: 0,
    z: 0
  };
  tween = new TWEEN.Tween(line.position).to(target, 20000).onUpdate(function() {
    line.geometry.verticesNeedUpdate = true;
  }).start();
};

animate = function() {
  renderer.render(scene, camera);
  requestAnimationFrame(animate);
  next.x += 1;
  TWEEN.update();
};

start = function() {
  initThree();
  initCamera();
  initObject();
  tweens();
  animate();
};

start();

//# sourceMappingURL=line_animate1.js.map
