// Generated by CoffeeScript 1.9.1
var cam_pos, make_pos, make_rotate, rnd;

rnd = function(x) {
  return Math.floor(Math.random() * x);
};

make_pos = function(O, X, Y, Z) {
  O.position.set(rnd(X), rnd(Y), rnd(Z));
};

make_rotate = function(O, X, Y, Z) {
  O.rotation.set(rnd(X), rnd(Y), rnd(Z));
};

cam_pos = function(camera, X, Y, Z) {
  camera.position.x = X;
  camera.position.y = Y;
  camera.position.z = Z;
};

var cam_up;

cam_up = function(camera,X,Y,Z){
  camera.up.set(X,Y,Z);
};
//# sourceMappingURL=module.js.map
